name: iziFile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  dartssh2: ^2.8.2
  data_table_2: ^2.5.8
  device_info_plus: ^10.1.0
  dio: ^5.3.3
  dropdown_button2: ^2.3.9
  file_picker: ^6.0.0
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  icons_launcher: ^2.1.7
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  xterm: ^4.0.0
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
icons_launcher:
  image_path: "assets/images/icon.png"
  platforms:
    windows:
      enable: true
      image_path: "assets/images/icon.png"
    android:
      enable: true
      image_path: "assets/images/icon.png"
